### ISSUE TITLE
kaliii

### ISSUE THREAD

**Issue by QuiverlyRivalry** [kaliiks/SkyGiants#1]
kaliiiiiiiii its me Quivvvv friend of Zenith hiiiiiiiiiii

**Comment by kaliiks** [comment]
Hi

**Comment by QuiverlyRivalry** [comment]
hi i used to be staff on mimedox xD

**Comment by kaliiks** [comment]
Do u have telegram?

**Comment by kaliiks** [comment]
Do u have telegram?

**Comment by QuiverlyRivalry** [comment]
No but have discord

**Comment by kaliiks** [comment]
I know

**Comment by QuiverlyRivalry** [comment]
do u have it?

**Comment by kaliiks** [comment]
Yes check it and u see ._.

**Comment by QuiverlyRivalry** [comment]
Last question are you soft macroon?

**Comment by kaliiks** [comment]
Go to discord answer is here
